// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcURF4W9p0s0CFhPMHR1pPT553ClAnivo',
    appId: '1:301274263499:web:fb02003f5441f055d8904e',
    messagingSenderId: '301274263499',
    projectId: 'miraclemoney-9924c',
    authDomain: 'miraclemoney-9924c.firebaseapp.com',
    storageBucket: 'miraclemoney-9924c.firebasestorage.app',
    measurementId: 'G-WBKKZ2MSRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJijl5k2cp0ffvMXBlLY6mucqk54Nr1vc',
    appId: '1:301274263499:android:8027e26f566c3050d8904e',
    messagingSenderId: '301274263499',
    projectId: 'miraclemoney-9924c',
    storageBucket: 'miraclemoney-9924c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmXY1OUSulOs48Qpn91PcWPqXjnMNBDU',
    appId: '1:301274263499:ios:463a9609e5a84234d8904e',
    messagingSenderId: '301274263499',
    projectId: 'miraclemoney-9924c',
    storageBucket: 'miraclemoney-9924c.firebasestorage.app',
    androidClientId:
        '301274263499-r504fq4n88kmfj0lfqihtgca2gns1rcv.apps.googleusercontent.com',
    iosClientId:
        '301274263499-6v3b9ka81ok7ih3e7erkeln3an5om8q6.apps.googleusercontent.com',
    iosBundleId: 'com.miraclemoney.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmXY1OUSulOs48Qpn91PcWPqXjnMNBDU',
    appId: '1:301274263499:ios:463a9609e5a84234d8904e',
    messagingSenderId: '301274263499',
    projectId: 'miraclemoney-9924c',
    storageBucket: 'miraclemoney-9924c.firebasestorage.app',
    androidClientId:
        '301274263499-r504fq4n88kmfj0lfqihtgca2gns1rcv.apps.googleusercontent.com',
    iosClientId:
        '301274263499-6v3b9ka81ok7ih3e7erkeln3an5om8q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.miraclemoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcURF4W9p0s0CFhPMHR1pPT553ClAnivo',
    appId: '1:301274263499:web:b16b38deb013d7ded8904e',
    messagingSenderId: '301274263499',
    projectId: 'miraclemoney-9924c',
    authDomain: 'miraclemoney-9924c.firebaseapp.com',
    storageBucket: 'miraclemoney-9924c.firebasestorage.app',
    measurementId: 'G-3NB239CR9W',
  );
}
